
bin := 'binaries/'


remove-function-pointers:
    {{bin}}cbmc --show-goto-functions listings/remove_function_pointers.c | tail -26

linking-cprover-lib:
    {{bin}}cbmc --show-goto-functions listings/linking_cprover_lib.c

instrument-preconditions:
    {{bin}}cbmc --show-goto-functions listings/instrument_precond.c | tail -39

remove-returns:
    {{bin}}cbmc --show-goto-functions listings/remove_return.c | tail -33

rewrite-union:
    {{bin}}cbmc --show-goto-functions listings/rewrite_union.c | tail -17

label-properties:
    {{bin}}cbmc --bounds-check listings/demo_prop_names.c
