
bin := 'binaries/'


remove-function-pointers:
    {{bin}}cbmc --show-goto-functions listings/remove_function_pointers.c | tail -26

linking-cprover-lib:
    {{bin}}cbmc --show-goto-functions listings/linking_cprover_lib.c

instrument-preconditions:
    {{bin}}cbmc --show-goto-functions listings/instrument_precond.c | tail -39

remove-returns:
    {{bin}}cbmc --show-goto-functions listings/remove_return.c | tail -33

rewrite-union:
    {{bin}}cbmc --show-goto-functions listings/rewrite_union.c | tail -17

label-properties:
    {{bin}}cbmc --bounds-check listings/demo_prop_names.c

goto-checkc-div-zero:
    {{bin}}cbmc --show-goto-functions listings/div_zero.c > no_instr.goto.txt
    {{bin}}cbmc --div-by-zero-check --show-goto-functions listings/div_zero.c > instr.goto.txt
    -diff no_instr.goto.txt instr.goto.txt
    rm no_instr.goto.txt instr.goto.txt

remove-complex:
    {{bin}}cbmc --show-goto-functions listings/complex.c | tail -17

adjust-float-expressions:
    {{bin}}cbmc --show-goto-functions listings/float_demo.c | tail -27

nondet-static:
    {{bin}}goto-cc -o nondet_static.goto nondet_static.c
    {{bin}}cbmc nondet_static.goto
    {{bin}}goto-instrument --nondet-static nondet_static.goto nondet_static.instr.goto
    -{{bin}}cbmc nondet_static_instr.goto
    {{bin}}goto-inspect --show-goto-functions nondet_static.goto
    {{bin}}goto-inspect --show-goto-functions nondet_static.instr.goto
    rm nondet_static.goto nondet_static_instr.goto
    
malloc-may-fail:
    {{bin}}cbmc listings/malloc_fail.c
    {{bin}}cbmc --malloc-may-fail --malloc-fail-null listings/malloc_fail.c
